INSERT INTO USERS (USER_ID, ID, PASSWORD, NAME, PHONE_NUM, BIRTH, TYPE, ACTIVATED) VALUES (1, 'adminid', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi','adminname','0000', '2000-01-01','admin' , 1 );
INSERT INTO USERS (USER_ID, ID, PASSWORD, NAME, PHONE_NUM, BIRTH, TYPE, ACTIVATED) VALUES (2, 'userid', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi','username','0000', '1999-01-01' ,'user', 1 );


INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (2, 'ROLE_USER');
