


INSERT INTO USERS (USER_ID, ID, PASSWORD, NAME, DATE_OF_BIRTH, TYPE, ACTIVATED) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin','2000-04-23','admin', 1);
INSERT INTO USERS (USER_ID, ID, PASSWORD, NAME, DATE_OF_BIRTH, TYPE, ACTIVATED) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user','2022-05-01','user', 1);
INSERT INTO USERS (USER_ID, ID, PASSWORD, NAME, DATE_OF_BIRTH, TYPE, ACTIVATED) VALUES (3, 'k1h2fls', 'k1h21394', 'hyelin','2022-05-01','user', 1);

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_USER');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_USER');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (2, 'ROLE_USER');