/**
 * 테스트를 위해 임포트 하여 사용할 데이터 및 상수 모음
 */

const constants = {
  MENU_ITEMS: [
    {
      category: 'Coffee',
      id: '1391039',
      name: '아이스 아메리카노',
      temp: 'Ice',
      size: 'Tall',
      price: '4,000',
      date: '2021.11.30',
    },
    {
      category: 'Coffee',
      id: '13947839',
      name: '토피넛 라떼',
      temp: 'Ice, Hot',
      size: 'Tall, Grande, Venti',
      price: '6,000',
      date: '2022.4.20',
    },
    {
      category: 'Non-Coffee',
      id: '1414612',
      name: '초코 라떼',
      temp: 'Ice, Hot',
      size: 'Tall, Grande',
      price: '5,000',
      date: '2021.1.30',
    },
    {
      category: 'Coffee',
      id: '13967839',
      name: '카라멜 마키아또',
      temp: 'Ice, Hot',
      size: 'Tall, Venti',
      price: '5,600',
      date: '2022.4.20',
    },
    {
      category: 'Non-Coffee',
      id: '14333612',
      name: '레몬에이드',
      temp: 'Ice',
      size: 'Tall, Grande, Venti',
      price: '7,000',
      date: '2021.7.19',
    },
    {
      category: 'Tea',
      id: '1245666',
      name: '캐모마일 티',
      temp: 'Ice, Hot',
      size: 'Tall, Grande, Venti',
      price: '4,500',
      date: '2021.3.2',
    },
    {
      category: 'Coffee',
      id: '13934513',
      name: '카푸치노',
      temp: 'Hot',
      size: 'Tall, Venti',
      price: '5,500',
      date: '2022.01.01',
    },
  ],
  CATEGORIES: [
    {
      name: 'Coffee',
      id: '1391039',
    },
    {
      name: 'Non-Coffee',
      id: '1414612',
    },
    {
      name: 'Tea',
      id: '1245666',
    },
  ],
  ORDER: {
    orders: [
      {
        menu: {
          category: 'Non-Coffee',
          id: '1414612',
          name: '초코 라떼',
          temp: 'Ice, Hot',
          size: 'Tall, Grande',
          price: '5,000',
          date: '2021.1.30',
        },
        quantity: 1,
      },
      {
        menu: {
          category: 'Coffee',
          id: '13967839',
          name: '카라멜 마키아또',
          temp: 'Ice, Hot',
          size: 'Tall, Venti',
          price: '5,600',
          date: '2022.4.20',
        },
        quantity: 2,
      },
      {
        menu: {
          category: 'Non-Coffee',
          id: '14333612',
          name: '레몬에이드',
          temp: 'Ice',
          size: 'Tall, Grande, Venti',
          price: '7,000',
          date: '2021.7.19',
        },
        quantity: 1,
      },
      {
        menu: {
          category: 'Tea',
          id: '1245666',
          name: '캐모마일 티',
          temp: 'Ice, Hot',
          size: 'Tall, Grande, Venti',
          price: '4,500',
          date: '2021.3.2',
        },
        quantity: 4,
      },
    ],
    takeout: false,
    total: 40000,
  },
  ORDER_ITEMS: [
    {
      order_number: '30',
      time: '15:30:43',
      table: 1,
      history: '아이스 아메리카노 에이드/Ice/Venti 크로플',
      state: 'ready',
      price: '16,000',
    },
    {
      order_number: '29',
      time: '15:27:03',
      table: 3,
      history: '카페라떼/Hot/Tall 블루베리마카롱',
      state: 'ready',
      price: '9 ,000',
    },
    {
      order_number: '28',
      time: '14:50:21',
      table: 7,
      history: '카페라떼/Hot/Tall 카푸치노/Hot/Venti',
      state: 'done',
      price: '11,000',
    },
    {
      order_number: '27',
      time: '14:10:46',
      table: 5,
      history: '아이스아메리카노 레몬크림마카롱',
      state: 'ready',
      price: '8,000',
    },
    {
      order_number: '26',
      time: '14:08:06',
      table: 6,
      history: '카모마일 티',
      state: 'done',
      price: '4,500',
    },
    {
      order_number: '25',
      time: '14:08:06',
      table: 2,
      history: '아이스 아메리카노/Tall 아이스티/Tall',
      state: 'done',
      price: '7,500',
    },
    {
      order_number: '25',
      time: '14:08:06',
      table: 2,
      history: '아이스 아메리카노/Tall 아이스티/Tall',
      state: 'done',
      price: '7,500',
    },
    {
      order_number: '25',
      time: '14:08:06',
      table: 2,
      history: '아이스 아메리카노/Tall 아이스티/Tall',
      state: 'ready',
      price: '7,500',
    },
    {
      order_number: '25',
      time: '14:08:06',
      table: 2,
      history: '아이스 아메리카노/Tall 아이스티/Tall',
      state: 'ready',
      price: '7,500',
    },
    {
      table: 10,
      state: 'empty',
    },
  ],
};
export default constants;
